"""The three operator secrets the sign-in reads.

They are read from files in ``MOH_SECRETS_DIR`` (``/run/secrets`` in the
stack, where swarm mounts them) and never from environment variables: a value
in the environment shows up in ``/proc/<pid>/environ`` and in crash reports,
which is the leak the deployment's entrypoint documents and asked the maintainers to close for new
secrets. the design reads the CalDAV credential the same way.

A missing or empty file means "not configured". Only the passphrase changes
what the API does when it is absent — sign-in is then off and the app is open,
which is the demo's behaviour; a deployment's entrypoint refuses to start the
API without it.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

PASSPHRASE_SECRET = "moh_household_passphrase"
SERVICE_TOKEN_SECRET = "moh_service_token"
LUNETTE_TOKEN_SECRET = "moh_lunette_token"

#: the design. Long enough that the rate limit, not the length, is what stops
#: guessing; short enough to type on a phone in a garden.
MIN_PASSPHRASE_LENGTH = 12

#: Tokens are generated by the operator with `openssl rand`; anything shorter
#: than this was not.
MIN_TOKEN_LENGTH = 24

DEFAULT_SECRETS_DIR = "/run/secrets"


class AuthConfigError(RuntimeError):
    """A secret exists but cannot be used. The message names the secret, never
    its value."""


@dataclass(frozen=True, slots=True)
class AuthSecrets:
    passphrase: str | None
    service_token: str | None
    lunette_token: str | None

    @property
    def enforcing(self) -> bool:
        """Sign-in is required exactly when a passphrase is configured."""
        return self.passphrase is not None


def secrets_dir() -> Path:
    return Path(os.environ.get("MOH_SECRETS_DIR") or DEFAULT_SECRETS_DIR)


def _read(directory: Path, name: str) -> str | None:
    path = directory / name
    try:
        value = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as error:  # permission, a directory where a file should be
        raise AuthConfigError(
            f"{name} exists but cannot be read: {error.strerror}"
        ) from None
    # Trailing newlines only, as the entrypoint does: `openssl rand > file`
    # leaves one, and a passphrase that silently gains a newline cannot be typed.
    value = value.rstrip("\r\n")
    return value or None


def load_secrets(directory: Path | None = None) -> AuthSecrets:
    directory = directory or secrets_dir()
    passphrase = _read(directory, PASSPHRASE_SECRET)
    service_token = _read(directory, SERVICE_TOKEN_SECRET)
    lunette_token = _read(directory, LUNETTE_TOKEN_SECRET)

    if passphrase is not None and len(passphrase) < MIN_PASSPHRASE_LENGTH:
        raise AuthConfigError(
            f"{PASSPHRASE_SECRET} is shorter than {MIN_PASSPHRASE_LENGTH} characters. "
            "Recreate it with a longer passphrase (docs/deploy/README.md §6)."
        )
    for name, token in (
        (SERVICE_TOKEN_SECRET, service_token),
        (LUNETTE_TOKEN_SECRET, lunette_token),
    ):
        if token is not None and len(token) < MIN_TOKEN_LENGTH:
            raise AuthConfigError(
                f"{name} is shorter than {MIN_TOKEN_LENGTH} characters. "
                "Generate it with `openssl rand -base64 32` (docs/deploy/README.md §6)."
            )
    return AuthSecrets(passphrase, service_token, lunette_token)
