#!/bin/sh
# The calendar-push secrets, as a stack overlay. The deployment.
#
#   docker secret ls --format '{{.Name}}' | scripts/caldav_overlay.sh > overlay.yml
#   docker stack deploy -c infra/stack/docker-stack.yml -c overlay.yml moh
#
# Each CalDAV feed's credential is a swarm secret named moh_caldav_<feed_id>
#, created by the operator and handed to the API with
# `docker service update --secret-add`. The stack file cannot name them — they
# are per feed, and the repository never knows a feed — and `docker stack
# deploy` resets a service to exactly what the files it is given list. So
# every redeploy would quietly take every feed's credential away from the API,
# and push would go back to "awaiting the operator" with nothing to say why.
#
# This reads secret names on stdin, keeps the moh_caldav_ ones, and prints an
# overlay that lists them on the api service (the only service that pushes).
# `make stack-deploy` passes it as a second -c file. Names only: a secret's
# content never passes through here. No matching name, no output, and the
# deploy runs with the stack file alone.

set -eu

names=$(grep -E '^moh_caldav_[A-Za-z0-9-]+$' || true)
[ -n "$names" ] || exit 0

echo "# Generated by scripts/caldav_overlay.sh at deploy time. Not a file to edit."
echo "services:"
echo "  api:"
echo "    secrets:"
for name in $names; do
  echo "      - $name"
done
echo "secrets:"
for name in $names; do
  echo "  $name:"
  echo "    external: true"
done
